# Site settings
title: Loch Lyme Lodge website
email: info@lochlymelodge.com
description: > # this means to ignore newlines until "baseurl:"
  A site that tells about the wonders of Loch Lyme Lodge
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
github_username: richb-hanover

# Build settings
markdown: kramdown
